project:
        name: taskcat-example
        regions: 
               - us-east-1
tests:
        iam-test:
                parameters:
                        ManagedPolicy: None
                        Path: /
                        PolicyName: IAMTest
                        RoleName: None
                template: ./test-iam-policy.yml

